import { ModuleArea, type Module } from "./types";

export const modules: Module[] = [
  { id: 1, title: "Mentoring", credits: 1, area: ModuleArea.Sonstiges, ws: true, ss: false},
  { id: 2, title: "Programmierung", credits: 8, area: ModuleArea.Praktische, ws: true, ss: false},
  { id: 3, title: "Technische Informatik", credits: 6, area: ModuleArea.Technische, ws: true, ss: true},
  { id: 4, title: "Analysis für Informatik", credits: 8, area: ModuleArea.Mathe, ws: true, ss: false},
  { id: 5, title: "Diskrete Strukturen", credits: 6, area: ModuleArea.Mathe, ws: true, ss: false},
  { id: 6, title: "Datenstrukturen und Algorithmen", credits: 7, area: ModuleArea.Praktische, ws: true, ss: true},
  { id: 7, title: "Betriebssysteme und Systemsoftware", credits: 7, area: ModuleArea.Technische, ws: false, ss: true},
  { id: 8, title: "Lineare Algebra", credits: 6, area: ModuleArea.Mathe, ws: false, ss: true},
  { id: 9, title: "Formale Systeme, Automaten, Prozesse", credits: 6, area: ModuleArea.Theoretische, ws: true, ss: true},
  { id: 10, title: "Proseminar", credits: 4, area: ModuleArea.Sonstiges, ws: true, ss: true},
  { id: 11, title: "Softwaretechnik", credits: 6, area: ModuleArea.Praktische, ws: true, ss: false},
  { id: 12, title: "Daten-kommunikation", credits: 6, area: ModuleArea.Technische, ws: false, ss: true},
  { id: 13, title: "PSP", credits: 8, area: ModuleArea.Technische, ws: true, ss: true},
  { id: 14, title: "Berechenbarkeit und Komplexität", credits: 7, area: ModuleArea.Theoretische, ws: true, ss: true},
  { id: 15, title: "Datenbanken und Informationssysteme", credits: 6, area: ModuleArea.Praktische, ws: true, ss: true},
  { id: 16, title: "Mathematische Logik", credits: 7, area: ModuleArea.Theoretische, ws: true, ss: true},
  { id: 17, title: "Stochastik", credits: 6, area: ModuleArea.Mathe, ws: true, ss: true},
  { id: 18, title: "SPP", credits: 6, area: ModuleArea.Sonstiges, ws: true, ss: true},
  { id: 19, title: "Machine Learning and Data Science", credits: 6, area: ModuleArea.Praktische, ws: true, ss: false},
  { id: 20, title: "IT-Security", credits: 4, area: ModuleArea.Technische, ws: true, ss: false},
  { id: 21, title: "Seminar", credits: 4, area: ModuleArea.Sonstiges, ws: true, ss: true},
  { id: 22, title: "Nicht-technisches Wahlfach", credits: 4, area: ModuleArea.Sonstiges, ws: true, ss: false},
  { id: 23, title: "Bachelorarbeit", credits: 15, area: ModuleArea.Sonstiges, ws: true, ss: true},
  { id: 24, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
  { id: 25, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
  { id: 26, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
  { id: 27, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
  { id: 28, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
  { id: 29, title: "Wahlpflich/Anw. Modul", credits: 6, area: ModuleArea.Wahl, ws: true, ss: true},
];
